---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: 'Creating PostgreSQL folder'
  file:
    dest: '{{ item }}'
    state: directory
    owner: '{{ pgsql_user }}'
    group: '{{ pgsql_group }}'
    mode: 0755
  with_items:
    - '{{ pgsql_folder }}'

- name: 'Configure PostgreSQL kernel parameters'
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
  with_items:
    - '{{ pgsql_kernel_parameters }}'

- name: 'Set PostgreSQL system-wide PATH parameters'
  lineinfile: 
    dest: '/etc/profile'
    line: "export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:{% if pgsql_releases == 'PostgresPro' %}/usr/pgpro-9.6/bin{% else %}/usr/pgsql-9.6/bin{% endif %}"

- name: 'Check if PostgreSQL tablespace exists'
  stat:
    path: '{{ item }}'
  with_items:
    - '{{ pgsql_path }}/pgsql/PG_VERSION'
  register: result

- name: 'Initializes the PostgreSQL system tables'
  shell: /bin/su - {{ pgsql_user }} -c "initdb -D {{ pgsql_path }}/pgsql"
  when: 
    - not result.results[0].stat.exists
  register: result

- name: 'Include specific tasks for {{ pgsql_releases }} release'
  include: '{{ pgsql_releases }}.yml'
  when: result|changed

- name: 'Install PostgreSQL prometheus exporter'
  include: 'postgres_exporter.yml'

- name: Ensure MTA service is enabled
  systemd:
    name: 'postfix.service'
    enabled: 'yes'
    state: 'started'
  when:
    - ansible_distribution_major_version|int > 6