---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: 'Creating {{ pgsql_releases }} folder'
  file:
    dest: '{{ item }}'
    state: directory
    owner: '{{ pgsql_user }}'
    group: '{{ pgsql_group }}'
    mode: 0755
  with_items:
    - '{{ pgsql_folder }}'

- name: 'Configure {{ pgsql_releases }} kernel parameters'
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
  with_items:
    - '{{ pgsql_kernel_parameters }}'

- name: 'Set system-wide PATH parameters'
  lineinfile: 
    dest: '/etc/profile'
    line: "export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/pgpro-9.6/bin"

- name: 'Check if {{ pgsql_releases }} tablespace exists'
  stat:
    path: '{{ item }}'
  with_items:
    - '{{ pgsql_path }}/pgsql/PG_VERSION'
  register: result

- name: 'Initializes the {{ pgsql_releases }} system tables'
  shell: /bin/su - {{ pgsql_user }} -c "initdb -D {{ pgsql_path }}/pgsql"
  when: 
    - not result.results[0].stat.exists
  register: result

- name: 'Configure {{ pgsql_releases }}'
  include: configureation.yml
  when: result|changed