---
- name: Add PostgreSQL prometheus exporter YUM repositories
  yum_repository:
    name: '{{ pgsql_exporter_repo_name }}'
    description: '{{ pgsql_exporter_repo_name }} YUM repository'
    file: '{{ pgsql_exporter_repo_name }}'
    baseurl: '{{ pgsql_exporter_repo_url }}'
    gpgcheck: no

- name: Install the PostgreSQL prometheus exporter
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ pgsql_exporter_packages }}'

- name: 'Add PostgreSQL prometheus exporter data source'
  lineinfile:
    state: present
    dest: '/usr/lib/systemd/system/postgres_exporter.service'
    insertafter: '^\[Service\]'
    regexp: '^Environment='
    line: 'Environment="DATA_SOURCE_NAME=postgresql://postgres:{{ db_sa_pass }}@127.0.0.1:5432/postgres?sslmode=disable"'
  no_log: true
  register: systemd_update

- name: PostgreSQL prometheus exporter configure file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_items:
    - { src: 'postgres_exporter', dest: '/etc/default/' }    
  register: conf_update

- name: Ensure PostgreSQL prometheus exporter service is enabled
  systemd:
    name: 'postgres_exporter.service'
    enabled: 'yes'
    state: 'started'
    daemon_reload: yes
  when:
    - systemd_update.changed or conf_update.changed

- name: Ensure PostgreSQL prometheus exporter firewall port is allow
  firewalld:
    port: '{{ pgsql_exporter_port }}/tcp'
    permanent: 'true'
    state: 'enabled'
  register: result
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int > 6

- name: Reload firewalld service
  service:
    name: firewalld
    state: reloaded
  when: result.changed

- name: Register exporter service with an http health check
  uri:
    url: 'http://{{ item }}:{{ consul_http_port }}/v1/agent/service/register'
    method: 'PUT'
    headers:
      X-Consul-Token: "{{ consul_exporter_token }}"
    body: '{"ID":"{{ inventory_hostname | upper }}_postgres_exporter","name":"postgres_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ pgsql_exporter_port }},"meta":{"instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ pgsql_exporter_port }}/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"5s"}]}'
    body_format: 'json'
  environment:
    no_proxy: '{{ item }}'
  with_items: '{{ consul_clients }}'
  when: consul_is_register
  no_log: true
