- name: 'PostgreSQL Configure & Scripts file transfer'
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: postgres
    group: postgres
    mode: '{{ item.mode }}'
  with_items:
    - { src: '.pgpass', dest: '/var/lib/pgsql/.pgpass', mode: '0600' }
    - { src: 'pgbackrest.conf', dest: '/etc/pgbackrest.conf', mode: '0755' }
    - { src: 'pgBackRest-runner.sh', dest: '/usr/local/bin/pgBackRest-runner.sh', mode: '0755' }

- name: 'Create the PostgreSQL backup stanza'
  shell: /bin/su - {{ pgsql_user }} -c "pgbackrest --stanza=database --log-level-console=info stanza-create"

- name: PostgreSQL configuration
  notify:
  - 'Server parameter Configuration'
  - 'Modify the default data folder'
  - 'Changing Limits for services'
  - 'Ensure service is enabled'
  - 'Change default password'

- name : 'PostgreSQL backup job'
  cron:
    name: 'PostgreSQL backup job'
    user: postgres
    minute: "{{ 59 |random}}"
    hour: "{{ (( inventory_hostname | hash | list | map('int',0,16) | sum ) % 2) + 1 }}"
    job: "/usr/local/bin/pgBackRest-runner.sh"

- name: Ensure MTA service is enabled
  systemd:
    name: 'postfix.service'
    enabled: 'yes'
    state: 'started'
  when:
    - ansible_distribution_major_version|int > 6
