---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: '{{ pgsql_releases }} installation'
  block:
    - name: 'Add {{ pgsql_releases }} YUM repositories'
      yum_repository:
        name: '{{ pgsql_repo_name }}'
        description: '{{ pgsql_repo_name }} YUM repository'
        file: '{{ pgsql_repo_name }}'
        baseurl: '{{ pgsql_repo_url }}'
        gpgcheck: 'no'
        timeout: '60'
    - name: Install the {{ pgsql_releases }} packages
      yum:
        name: '{{ ",".join(vars["pgsql_packages_" + pgsql_version]) }}'
        state: 'present'
        validate_certs: 'no'
        disable_gpg_check: 'yes'
      register: yum_status
      until: yum_status is succeeded
      retries: 3
      delay: 5
  when: pgsql_releases == 'PostgreSQL'

- name: '{{ pgsql_releases }} installation'
  block:
    - name: 'Add {{ pgsql_releases }} YUM repositories'
      yum_repository:
        name: '{{ pgpro_repo_name }}'
        description: '{{ pgpro_repo_name }} YUM repository'
        file: '{{ pgpro_repo_name }}'
        baseurl: '{{ pgpro_repo_url }}'
        gpgcheck: 'no'
        timeout: '60'
    - name: Install the {{ pgsql_releases }} packages
      yum:
        name: '{{ ",".join(vars["pgpro_packages_" + pgsql_version]) }}'
        state: 'present'
        validate_certs: 'no'
        disable_gpg_check: 'yes'
      register: yum_status
      until: yum_status is succeeded
      retries: 3
      delay: 5
  when: pgsql_releases == 'PostgresPro'