---
- name: '{{ pgsql_releases }} installation'
  block:
    - name: 'Add {{ pgsql_releases }} YUM repositories'
      yum_repository:
        name: '{{ pgsql_repo_name }}'
        description: '{{ pgsql_repo_name }} YUM repository'
        file: '{{ pgsql_repo_name }}'
        baseurl: '{{ pgsql_repo_url }}'
        gpgcheck: 'no'
        timeout: '60'
    - name: Install the {{ pgsql_releases }} packages
      yum:
        name: '{{ ",".join(vars["pgsql_packages_" + pgsql_version]) }}'
        state: 'present'
        validate_certs: 'no'
        disable_gpg_check: 'yes'
  when: pgsql_releases == 'PostgreSQL'

- name: '{{ pgsql_releases }} installation'
  block:
    - name: 'Add {{ pgsql_releases }} YUM repositories'
      yum_repository:
        name: '{{ pgpro_repo_name }}'
        description: '{{ pgpro_repo_name }} YUM repository'
        file: '{{ pgpro_repo_name }}'
        baseurl: '{{ pgpro_repo_url }}'
        gpgcheck: 'no'
        timeout: '60'
    - name: Install the {{ pgsql_releases }} packages
      yum:
        name: '{{ ",".join(vars["pgpro_packages_" + pgsql_version]) }}'
        state: 'present'
        validate_certs: 'no'
        disable_gpg_check: 'yes'
  when: pgsql_releases == 'PostgresPro'

- name: 'Ensure {{ pgsql_releases }} firewall port is allow'
  firewalld:
    port: '{{ pgsql_port }}/tcp'
    permanent: 'true'
    state: 'enabled'
  when:
    - ansible_distribution_major_version|int > 6
  register: result

- name: Reload firewalld service
  service:
    name: firewalld
    state: reloaded
  when:
    - result is changed
    - ansible_distribution_major_version|int > 6
